question=input("G'day to you darlin'! What exactly is your name? ")
print(question)
judgement=input("Wow...How unique! What is the origin of that name, may I ask? ")
print(judgement)
comment = ("Very, very interesting. Well, don't beat yourself up, not everyone can have a good name! ")
print(comment)
silence=("...*awkard silence*...")
print(silence)
demand=input("Well...don't you want to ask my name? ")
print(demand)
offense = ("Wait...I just realized I don't care what you want! I'm going to tell you regardless! My name is Gertrude, pleasure to meet ya! ")
print(offense)